### ISSUE TITLE
Remove Bootstrap section of config files for services in containers

### ISSUE THREAD

**Issue by mwyzhao** [Multi-Tier-Cloud/docker-driver#8]
With changes from https://github.com/Multi-Tier-Cloud/service-manager/issues/31, need to change microservices in containers to no longer have a bootstrap section in order to always use the environment variable. This is to enable changing bootstraps on the fly in case of changed circumstances.

**Comment by t-lin** [comment]
@michaelweiyuzhao @hivanco This has been resolved in Multi-Tier-Cloud/service-registry#20, no? Or is it talking about something else?

**Comment by hivanco** [comment]
Yeah this is resolved now
